### ISSUE TITLE
dont

### ISSUE THREAD

**Issue by byCaptain** [WolverinDEV/Nyra#1]
work

**Comment by WolverinDEV** [comment]
?

**Comment by byCaptain** [comment]
anzeige raus. du machst dich übrigens auch strafbar :^)

**Comment by WolverinDEV** [comment]
Nein,
da es für Twerion programiert wurde und wie schon erwähnt ich mit einverständnis von Imad Al-Saleh das Projekt veröffentlichen durfte :)

**Comment by byCaptain** [comment]
Wir werdne sehen :^) Deine Kontaktdaten haben wir.

**Comment by WolverinDEV** [comment]
Haha ich wüsste dann gerne mal woher aber bitte :)
